@apiUrl = http://localhost:3030/notes

###
GET {{apiUrl}}

###
POST {{apiUrl}}
Content-Type: application/json

{
    "text": "My note"
}

### 
PATCH {{apiUrl}}/100
Content-Type: application/json

{
    "text": "My note"
}

###
DELETE {{apiUrl}}/100

###