#@apiUrl = http://localhost:3030/notes
@apiUrl = https://notes-fredde-23.azurewebsites.net/notes
@token = {{$dotenv TOKEN}}

###
GET {{apiUrl}}
Authorization: Bearer {{token}}


###
GET {{apiUrl}}/64f9a89c3192a9bf9d0e740a
Authorization: Bearer {{token}}

###
POST {{apiUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "text": "Ny note"
}

### 
PATCH {{apiUrl}}/6502ef443caace48e3aa61e9
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "text": "Ny note uppdaterad"
}

###
DELETE {{apiUrl}}/64f9aa07539b7df1d8de2397
Authorization: Bearer {{token}}

###